In [9]:
# !pip install librosa==0.8.0
# !pip install pydub==0.25.1
# !pip install numpy==1.19.5
# !pip install matplotlib==3.3.4
# !pip install tensorflow==2.4.1
# !pip install scikit-learn==0.24.1
# !pip install pillow==8.1.0

  Using cached numpy-1.19.5.zip (7.3 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'error'


  error: subprocess-exited-with-error
  
  Preparing metadata (pyproject.toml) did not run successfully.
  exit code: 1
  
  [202 lines of output]
  setup.py:67: RuntimeWarning: NumPy 1.19.5 may not yet support Python 3.11.
    warnings.warn(
  Running from numpy source directory.
  setup.py:480: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
    run_build = parse_setuppy_commands()
  Processing numpy/random\_bounded_integers.pxd.in
  Processing numpy/random\bit_generator.pyx
  Processing numpy/random\mtrand.pyx
  Processing numpy/random\_bounded_integers.pyx.in
  Processing numpy/random\_common.pyx
  Processing numpy/random\_generator.pyx
  Processing numpy/random\_mt19937.pyx
  Processing numpy/random\_pcg64.pyx
  Processing numpy/random\_philox.pyx
  Processing numpy/random\_sfc64.pyx
  Cythonizing sources
  blas_opt_info:
  blas_mkl_info:
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying fro

  Using cached matplotlib-3.3.4.tar.gz (37.9 MB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
  Using cached kiwisolver-1.4.5-cp311-cp311-win_amd64.whl.metadata (6.5 kB)
  Using cached pyparsing-3.1.2-py3-none-any.whl.metadata (5.1 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Using cached kiwisolver-1.4.5-cp311-cp311-win_amd64.whl (56 kB)
Using cached pyparsing-3.1.2-py3-none-any.whl (103 kB)
  Running setup.py clean for matplotlib
Failed to build matplotlib


  error: subprocess-exited-with-error
  
  python setup.py bdist_wheel did not run successfully.
  exit code: 1
  
  [592 lines of output]
  
  Edit setup.cfg to change the build options; suppress output with --quiet.
  
  BUILDING MATPLOTLIB
    matplotlib: yes [3.3.4]
        python: yes [3.11.9 | packaged by Anaconda, Inc. | (main, Apr 19 2024,
                    16:40:41) [MSC v.1916 64 bit (AMD64)]]
      platform: yes [win32]
   sample_data: yes [installing]
         tests: no  [skipping due to configuration]
        macosx: no  [Mac OS-X only]
  
  C:\Users\USER\anaconda3\envs\azz\Lib\site-packages\setuptools\__init__.py:81: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
  !!
  
          ********************************************************************************
          Requirements should be satisfied by a PEP 517 installer.
          If you are using pip, you can try `pip install --use-pep517`.
          *******************************

  Using cached scikit-learn-0.24.1.tar.gz (7.4 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Failed to build scikit-learn


  error: subprocess-exited-with-error
  
  exit code: 1
  
  [65 lines of output]
  <string>:17: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  Partial import of sklearn during the build process.
  <string>:116: DeprecationWarning:
  
    `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
    of the deprecation of `distutils` itself. It will be removed for
    Python >= 3.12. For older Python versions it will remain present.
    It is recommended to use `setuptools < 60.0` for those Python versions.
    For more details, see:
      https://numpy.org/devdocs/reference/distutils_status_migration.html
  
  
  INFO: No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  Traceback (most recent call last):
    File "C:\Users\USER\anaconda3\envs\azz\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
      main()
    File "C:\

  Using cached Pillow-8.1.0.tar.gz (44.9 MB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Running setup.py clean for pillow
Failed to build pillow


  error: subprocess-exited-with-error
  
  python setup.py bdist_wheel did not run successfully.
  exit code: 1
  
  [186 lines of output]
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-cpython-311
  creating build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\BdfFontFile.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\BlpImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\BmpImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\BufrStubImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\ContainerIO.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\CurImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\DcxImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\DdsImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\EpsImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
  copying src\PIL\ExifT

In [4]:
# !pip install tensorflow

  Using cached tensorflow-2.17.0-cp311-cp311-win_amd64.whl.metadata (3.2 kB)
  Using cached tensorflow_intel-2.17.0-cp311-cp311-win_amd64.whl.metadata (5.0 kB)
  Using cached absl_py-2.1.0-py3-none-any.whl.metadata (2.3 kB)
  Using cached astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
  Using cached flatbuffers-24.3.25-py2.py3-none-any.whl.metadata (850 bytes)
  Using cached gast-0.6.0-py3-none-any.whl.metadata (1.3 kB)
  Using cached google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
  Using cached h5py-3.11.0-cp311-cp311-win_amd64.whl.metadata (2.5 kB)
  Using cached libclang-18.1.1-py2.py3-none-win_amd64.whl.metadata (5.3 kB)
  Using cached ml_dtypes-0.4.0-cp311-cp311-win_amd64.whl.metadata (20 kB)
  Using cached opt_einsum-3.3.0-py3-none-any.whl.metadata (6.5 kB)
  Using cached protobuf-4.25.3-cp310-abi3-win_amd64.whl.metadata (541 bytes)
  Using cached termcolor-2.4.0-py3-none-any.whl.metadata (6.1 kB)
  Using cached wrapt-1.16.0-cp311-cp311-win_amd64.whl.metadata (

In [10]:
import os
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from tensorflow.keras.preprocessing.image import load_img, img_to_array
import time

# 전체 코드 실행 시작 시간 기록
overall_start_time = time.time()
print(f"시작 시간: {time.ctime(overall_start_time)}")

# 데이터 디렉토리 설정
base_data_directory = './data/mfcc_data/'

# 이미지 크기 및 하이퍼파라미터 설정
img_height, img_width = 128, 128  # 이미지 크기 설정
num_classes = 9  # 클래스 수 (예: babycry, boil, carhorn, door, emergencysiren, firesiren, gas, glass, stillsiren)

# 데이터셋 준비
X = []
y = []

# 데이터 디렉토리에서 이미지 파일을 불러와서 리스트에 추가
for filename in os.listdir(base_data_directory):
    if filename.endswith('.png'):  # PNG 파일만 처리
        # 클래스 번호 추출
        class_number = int(filename.split('_')[0])
        # 이미지 파일 경로
        img_path = os.path.join(base_data_directory, filename)
        # 이미지 불러오기 및 전처리
        img = load_img(img_path, target_size=(img_height, img_width))  # 이미지 로드 및 크기 조정
        img_array = img_to_array(img) / 255.0  # 이미지를 배열로 변환 및 정규화
        X.append(img_array.flatten())  # 이미지 배열을 평탄화하여 X 리스트에 추가
        y.append(class_number)  # 클래스 번호를 y 리스트에 추가

# 리스트를 numpy 배열로 변환
X = np.array(X)
y = np.array(y)

# 데이터셋을 학습 세트와 검증 세트로 나누기
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.3, random_state=42)

# 이미지 데이터를 원래 2D 형태로 유지 (공간적 구조를 잃지 않도록)
# Random Forest는 1D 벡터를 입력으로 받으므로, 이미지를 평탄화한 후 사용합니다.
# 그러나 이렇게 하면 공간적 구조를 잃게 됩니다.
# 이를 보완하기 위해 각 픽셀 위치 정보를 특징으로 포함합니다.

# 이미지를 2D 배열 형태로 변환
X_train_reshaped = X_train.reshape(-1, img_height, img_width, 3)
X_val_reshaped = X_val.reshape(-1, img_height, img_width, 3)

# 각 픽셀 위치를 특징으로 변환
# 이미지의 각 픽셀 (i, j)의 RGB 값을 사용하여 특징 벡터를 구성합니다.
X_train_features = np.zeros((X_train.shape[0], img_height * img_width * 3))
X_val_features = np.zeros((X_val.shape[0], img_height * img_width * 3))

# 각 픽셀의 위치를 반영하여 특징 벡터 생성
for i in range(img_height):
    for j in range(img_width):
        for k in range(3):  # RGB 채널
            X_train_features[:, i*img_width*3 + j*3 + k] = X_train_reshaped[:, i, j, k]
            X_val_features[:, i*img_width*3 + j*3 + k] = X_val_reshaped[:, i, j, k]

# Random Forest 모델 생성 및 학습
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train_features, y_train)

# 모델 평가
y_val_pred = rf_model.predict(X_val_features)

# 성능 보고서 및 혼동 행렬 출력
print("Classification Report:\n")
print(classification_report(y_val, y_val_pred, target_names=[str(i) for i in range(num_classes)]))
print("Confusion Matrix:\n")
print(confusion_matrix(y_val, y_val_pred))

# 전체 코드 실행 종료 시간 기록
overall_end_time = time.time()
print(f"종료 시간: {time.ctime(overall_end_time)}")
print(f"소요 시간: {overall_end_time - overall_start_time:.2f}초")


시작 시간: Wed Jul 24 17:59:24 2024
Classification Report:

              precision    recall  f1-score   support

           0       1.00      0.99      0.99       463
           1       1.00      0.99      1.00       452
           2       0.97      0.89      0.92       463
           3       0.99      1.00      0.99       437
           4       0.98      0.96      0.97       446
           5       0.90      0.98      0.94       454
           6       1.00      0.98      0.99       446
           7       0.99      1.00      0.99       450
           8       0.98      0.99      0.98       439

    accuracy                           0.98      4050
   macro avg       0.98      0.98      0.98      4050
weighted avg       0.98      0.98      0.98      4050

Confusion Matrix:

[[457   1   2   3   0   0   0   0   0]
 [  0 449   0   0   0   0   2   1   0]
 [  0   0 410   0   7  46   0   0   0]
 [  0   0   0 437   0   0   0   0   0]
 [  0   0   3   0 430   3   0   0  10]
 [  0   0   7   0   0 447